### ISSUE TITLE
Data Collection and Storage from Query Node

### ISSUE THREAD

**Issue by chrlschwb** [Joystream/dashboard-api#3]
The following data will be fetched from QN, stored and made available on an API endpoint.

- Number of channels
- Number of videos
- Number of comments
- Number of reactions
- Number of video NFTs
- Number of video NFT sales
- total price of sold video NFTs
- data of council members
- data of leads
- total minting
- minting for worker reward
- minting for spending proposal
- minting for validator payout 
- minting for creator payout

**Comment by bedeho** [comment]
Actually the following don't make any sense as time series data points do they

- total minting
- minting for worker reward
- minting for spending proposal
- minting for validator payout
- minting for creator payout

These are all metrics over _a period of time_, while time series only hold values for _a point in time_. The only way to amke this work is that each time series data point holds value _over the period of time since the last time series value_, something like that, but its still kind of weird. Alternatively, you are going to have to store each individual minting event as its own data point, so each time you query QN, you get many data points of the same type, and you store them all as local time series values at different times, not the times at which you are calling. Anyway, this is all too unclear, and I think you did not properly specify how we do this in your breakdown either https://github.com/Joystream/dashboard-api/issues/2.

So, whatever you have in mind, specify it precisely in terms of what exactly you will store, how you will obtain it from QN, and verify whether QN does indeed have it.
